### PR TITLE
Setup github actions

### PR DESCRIPTION
**Pull request by zhmushan**

### CODE REVIEW

**Comment by zhmushan** [comment]
@HerringtonDarkholme Any ideas on fixing the diverging_sub_expression error?

**Comment by HerringtonDarkholme** [comment]
Thanks for setting up GH actions!
These are inherently todo and I need to implement them.

**Comment by zhmushan** [comment]
Consider merging this PR? Although it can only be red before todo is implemented

**Comment by HerringtonDarkholme** [comment]
@zhmushan I think denying todo! is too strict for a new project. Can we relax the clippy option `-D clippy:all` ?

**Comment by zhmushan** [comment]
@HerringtonDarkholme This rule does not prohibit `todo!()`. This error is caused by passing `todo!()` to `emit_error`. It should be `SourceLocation`.

**Pull request merged**
